### ISSUE TITLE
crash when attempting to play a video

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#1033]
probably related to #1032 

tested with .mov and .mp4
(no HAP)

**Comment by jcelerier** [comment]
can you attach a crash log ?

**Comment by thibaudk** [comment]
```
           PID: 10833 (ossia-score)
           UID: 1000 (scrime)
           GID: 1000 (scrime)
        Signal: 11 (SEGV)
     Timestamp: Thu 2020-05-28 15:56:28 CEST (2min 46s ago)
  Command Line: ./ossia-score
    Executable: /home/scrime/Documents/repos/build-score-Desktop-Release/ossia-score
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (scrime)
       Boot ID: a656fcfcbddb4626b2970e165df59a6f
    Machine ID: f9a45a3700934fb3b5d6c02e658dc4e9
      Hostname: scrime-Latitude-3400
       Storage: /var/lib/systemd/coredump/core.ossia-score.1000.a656fcfcbddb4626b2970e165df59a6f.10833.1590674188000000000000.lz4
       Message: Process 10833 (ossia-score) of user 1000 dumped core.
                
                Stack trace of thread 10833:
                #0  0x00007fd6078c300d n/a (/home/scrime/Documents/repos/Qt/gcc_64/lib/libQt5Gui.so.5.15.0 + 0x52a00d)
```

**Comment by thibaudk** [comment]
is this enough ?

**Comment by jcelerier** [comment]
no :p  
can you run `coredumpctl gdb`, that should have the whole trace

**Comment by jcelerier** [comment]
(and type `bt` to get the stack trace once gdb has loaded)

**Comment by thibaudk** [comment]
```
(gdb) bt
#0  0x00007fd6078c300d in QVector<QShaderDescription::InOutVariable>::freeData(QTypedArrayData<QShaderDescription::InOutVariable>*) [clone .isra.31] () at /home/scrime/Documents/repos/Qt/gcc_64/lib/libQt5Gui.so.5
#1  0x00007fd6078c52fe in QShaderDescription::~QShaderDescription() () at /home/scrime/Documents/repos/Qt/gcc_64/lib/libQt5Gui.so.5
#2  0x00007fd6078cd885 in QShader::operator=(QShader const&) () at /home/scrime/Documents/repos/Qt/gcc_64/lib/libQt5Gui.so.5
#3  0x00000000019aa4d4 in NodeModel::setShaders(QString, QString) ()
#4  0x00000000019bf94e in YUV420Decoder::init(Renderer&, RenderedNode&) ()
#5  0x00000000019aadeb in RenderedNode::init(Renderer&) ()
#6  0x00000000019ace8b in Renderer::maybeRebuild() ()
#7  0x00000000019aced5 in Renderer::render(QRhiCommandBuffer&) ()
#8  0x00000000019d2c81 in Window::render() ()
#9  0x00000000019d28f3 in Window::event(QEvent*) ()
#10 0x00007fd60ed4713c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /home/scrime/Documents/repos/Qt/gcc_64/lib/libQt5Widgets.so.5
#11 0x00007fd60ed4dd10 in QApplication::notify(QObject*, QEvent*) () at /home/scrime/Documents/repos/Qt/gcc_64/lib/libQt5Widgets.so.5
#12 0x0000000001035211 in SafeQApplication::notify(QObject*, QEvent*) ()
#13 0x00007fd606e408f8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /home/scrime/Documents/repos/Qt/gcc_64/lib/libQt5Core.so.5
#14 0x00007fd6074f9626 in QPlatformWindow::windowEvent(QEvent*) () at /home/scrime/Documents/repos/Qt/gcc_64/lib/libQt5Gui.so.5
#15 0x00007fd60ed4dc8b in QApplication::notify(QObject*, QEvent*) () at /home/scrime/Documents/repos/Qt/gcc_64/lib/libQt5Widgets.so.5
#16 0x0000000001035211 in SafeQApplication::notify(QObject*, QEvent*) ()
#17 0x00007fd606e408f8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /home/scrime/Documents/repos/Qt/gcc_64/lib/libQt5Core.so.5
#18 0x00007fd606e9b5d9 in QTimerInfoList::activateTimers() () at /home/scrime/Documents/repos/Qt/gcc_64/lib/libQt5Core.so.5
#19 0x00007fd606e9bdb1 in timerSourceDispatch(_GSource*, int (*)(void*), void*) () at /home/scrime/Documents/repos/Qt/gcc_64/lib/libQt5Core.so.5
#20 0x00007fd602a00fbd in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007fd602a01240 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007fd602a012e3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007fd606e9c11c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /home/scrime/Documents/repos/Qt/gcc_64/lib/libQt5Core.so.5
#24 0x00007fd606e3f30a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /home/scrime/Documents/repos/Qt/gcc_64/lib/libQt5Core.so.5
#25 0x00007fd606e482b3 in QCoreApplication::exec() () at /home/scrime/Documents/repos/Qt/gcc_64/lib/libQt5Core.so.5
#26 0x0000000001000b20 in main ()
(gdb) 
```

**Comment by thibaudk** [comment]
it this it ?

**Comment by thibaudk** [comment]
I can also build in debug mode

**Comment by jcelerier** [comment]
yep, thanks !


-------
Jean-Michaël Celerier
http://www.jcelerier.name

**Comment by jcelerier** [comment]
can you also send the video files ?

**Comment by thibaudk** [comment]
Ok so the crash does not happen with the Appimage Release.
But the content CPU spike is still there

**Comment by thibaudk** [comment]
the appimage also gives out this log when playing the video

```
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (16947660 > 135).
digraph G {
}

[h264 @ 0x9fbf080] Error splitting the input into NAL units.
digraph G {
}

[h264 @ 0x9fbf080] Invalid NAL unit size (18666796 > 172).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18617644 > 159).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18355501 > 169).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18748716 > 172).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18748716 > 171).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18224429 > 174).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18355501 > 181).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18355489 > 160).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17831208 > 174).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18355497 > 163).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962281 > 163).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18224417 > 159).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962272 > 166).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962280 > 164).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962273 > 160).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18224425 > 165).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17831200 > 158).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962272 > 164).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962266 > 165).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17831201 > 165).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18224409 > 166).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962266 > 162).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962272 > 160).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18093352 > 166).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18093357 > 219).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (19404077 > 185).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (19928365 > 184).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (20190509 > 198).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (20059437 > 211).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (20059437 > 204).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (20190508 > 182).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (20321581 > 176).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (19797248 > 174).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (19535104 > 178).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (19010860 > 174).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18879785 > 169).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18486569 > 174).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18355496 > 167).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18224425 > 163).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962285 > 214).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (19273004 > 247).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (19797292 > 244).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (16947660 > 135).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18666796 > 172).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18617644 > 159).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18355501 > 169).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18748716 > 172).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18748716 > 171).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18224429 > 174).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18355501 > 181).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18355489 > 160).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17831208 > 174).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18355497 > 163).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962281 > 163).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18224417 > 159).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962272 > 166).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962280 > 164).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962273 > 160).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18224425 > 165).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17831200 > 158).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962272 > 164).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962266 > 165).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17831201 > 165).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18224409 > 166).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962266 > 162).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962272 > 160).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18093352 > 166).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18093357 > 219).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (19404077 > 185).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (19928365 > 184).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (20190509 > 198).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (20059437 > 211).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (20059437 > 204).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (20190508 > 182).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (20321581 > 176).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (19797248 > 174).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (19535104 > 178).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (19010860 > 174).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18879785 > 169).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18486569 > 174).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18355496 > 167).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18224425 > 163).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962285 > 214).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (19273004 > 247).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (19797292 > 244).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
```

**Comment by thibaudk** [comment]
the appimage also gives out this log when playing the video

```
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (16947660 > 135).
digraph G {
}

[h264 @ 0x9fbf080] Error splitting the input into NAL units.
digraph G {
}

[h264 @ 0x9fbf080] Invalid NAL unit size (18666796 > 172).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18617644 > 159).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18355501 > 169).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18748716 > 172).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18748716 > 171).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18224429 > 174).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18355501 > 181).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18355489 > 160).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17831208 > 174).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18355497 > 163).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962281 > 163).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18224417 > 159).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962272 > 166).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962280 > 164).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962273 > 160).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18224425 > 165).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17831200 > 158).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962272 > 164).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962266 > 165).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17831201 > 165).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18224409 > 166).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962266 > 162).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962272 > 160).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18093352 > 166).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18093357 > 219).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (19404077 > 185).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (19928365 > 184).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (20190509 > 198).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (20059437 > 211).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (20059437 > 204).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (20190508 > 182).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (20321581 > 176).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (19797248 > 174).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (19535104 > 178).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (19010860 > 174).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18879785 > 169).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18486569 > 174).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18355496 > 167).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18224425 > 163).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962285 > 214).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (19273004 > 247).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (19797292 > 244).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (16947660 > 135).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18666796 > 172).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18617644 > 159).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18355501 > 169).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18748716 > 172).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18748716 > 171).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18224429 > 174).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18355501 > 181).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18355489 > 160).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17831208 > 174).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18355497 > 163).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962281 > 163).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18224417 > 159).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962272 > 166).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962280 > 164).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962273 > 160).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18224425 > 165).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17831200 > 158).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962272 > 164).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962266 > 165).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17831201 > 165).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18224409 > 166).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962266 > 162).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962272 > 160).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18093352 > 166).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18093357 > 219).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (19404077 > 185).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (19928365 > 184).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (20190509 > 198).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (20059437 > 211).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (20059437 > 204).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (20190508 > 182).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (20321581 > 176).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (19797248 > 174).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (19535104 > 178).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (19010860 > 174).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18879785 > 169).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18486569 > 174).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18355496 > 167).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (18224425 > 163).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (17962285 > 214).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (19273004 > 247).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Invalid NAL unit size (19797292 > 244).
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
[h264 @ 0x9fbf080] Error splitting the input into NAL units.
```

**Comment by thibaudk** [comment]
accidentaly closed

**Comment by thibaudk** [comment]
Ok after, cleaning up and recompiling qtshadertools against Qt 5.15.0,
It does not crash.
Sory for the false alert

**Comment by jcelerier** [comment]
ah yeah, makes sense. cool that you could fix it !
