### ISSUE TITLE
crash on startup with the latest build

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#1044]
here is the crach log

```
           PID: 33726 (ossia-score)
           UID: 1000 (scrime)
           GID: 1000 (scrime)
        Signal: 6 (ABRT)
     Timestamp: Tue 2020-06-16 23:07:00 CEST (2min 17s ago)
  Command Line: ./ossia-score
    Executable: /home/scrime/Documents/repos/build-score-Desktop-Release/ossia-score
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (scrime)
       Boot ID: e2a86639b7cd4bc3a153a8bb67db5ce5
    Machine ID: f9a45a3700934fb3b5d6c02e658dc4e9
      Hostname: scrime-Latitude-3400
       Storage: /var/lib/systemd/coredump/core.ossia-score.1000.e2a86639b7cd4bc3a153a8bb67db5ce5.33726.1592341620000000000000.lz4
       Message: Process 33726 (ossia-score) of user 1000 dumped core.
                
                Stack trace of thread 33726:
                #0  0x00007f379055e18b __GI_raise (libc.so.6 + 0x4618b)
                #1  0x00007f379053d859 __GI_abort (libc.so.6 + 0x25859)
                #2  0x00007f37905a83ee __libc_message (libc.so.6 + 0x903ee)
                #3  0x00007f37905b047c malloc_printerr (libc.so.6 + 0x9847c)
                #4  0x00007f37905b412c _int_realloc (libc.so.6 + 0x9c12c)
                #5  0x00007f37905b62d6 __GI___libc_realloc (libc.so.6 + 0x9e2d6)
                #6  0x00007f37909c8009 n/a (/home/scrime/Documents/repos/Qt/gcc_64/lib/libQt5Core.so.5.15.0 + 0xc0009)

GNU gdb (Ubuntu 9.1-0ubuntu1) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/scrime/Documents/repos/build-score-Desktop-Release/ossia-score...
[New LWP 33726]
[New LWP 33731]
[New LWP 33729]
[New LWP 33736]
[New LWP 33738]
[New LWP 33737]
[New LWP 33742]
[New LWP 33728]
[New LWP 33730]
[New LWP 33732]
[New LWP 33741]
[New LWP 33739]
[New LWP 33734]
[New LWP 33727]
[New LWP 33735]
[New LWP 33733]
[New LWP 33740]

warning: Unexpected size of section `.reg-xstate/33726' in core file.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
--Type <RET> for more, q to quit, c to continue without paging--bt
Core was generated by `./ossia-score'.
Program terminated with signal SIGABRT, Aborted.

warning: Unexpected size of section `.reg-xstate/33726' in core file.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: Aucun fichier ou dossier de ce type.
[Current thread is 1 (Thread 0x7f37833ac180 (LWP 33726))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f379053d859 in __GI_abort () at abort.c:79
#2  0x00007f37905a83ee in __libc_message
    (action=action@entry=do_abort, fmt=fmt@entry=0x7f37906d2285 "%s\n")
    at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007f37905b047c in malloc_printerr
    (str=str@entry=0x7f37906d05a8 "realloc(): invalid next size")
    at malloc.c:5347
#4  0x00007f37905b412c in _int_realloc
    (av=av@entry=0x7f3790703b80 <main_arena>, oldp=oldp@entry=0x401adb0, oldsize=oldsize@entry=144, nb=272) at malloc.c:4564
#5  0x00007f37905b62d6 in __GI___libc_realloc (oldmem=0x401adc0, bytes=256)
    at malloc.c:3235
#6  0x00007f37909c8009 in QArrayData::reallocateUnaligned(QArrayData*, unsigned long, unsigned long, QFlags<QArrayData::AllocationOption>) ()
    at /home/scrime/Documents/repos/Qt/gcc_64/lib/libQt5Core.so.5
#7  0x00007f3790a4b7d3 in QString::reallocData(unsigned int, bool) ()
    at /home/scrime/Documents/repos/Qt/gcc_64/lib/libQt5Core.so.5
#8  0x00007f3790a4b858 in QString::resize(int) ()
    at /home/scrime/Documents/repos/Qt/gcc_64/lib/libQt5Core.so.5
#9  0x0000000000f98e77 in QString QStringBuilder<QString, char [8]>::convertTo<QString>() const ()
#10 0x0000000000f9683b in Scenario::Settings::View::View() ()
--Type <RET> for more, q to quit, c to continue without paging--
#11 0x0000000000f06af9 in score::SettingsDelegateFactory_T<Scenario::Settings::Model, Scenario::Settings::Presenter, Scenario::Settings::View>::makeView() ()
#12 0x0000000000d5be53 in score::Settings::setupSettingsPlugin(QSettings&, score::ApplicationContext const&, score::SettingsDelegateFactory&) ()
#13 0x0000000000cfff02 in score::GUIApplicationInterface::loadPluginData(score::Settings&, score::Presenter&) ()
#14 0x0000000000c9afc4 in Application::init() ()
#15 0x0000000000cca0e4 in main ()
```

**Comment by thibaudk** [comment]
could it be because my version of qt is 5.15.0 instead of 5.15.1 ?
I'll update and see.

**Comment by jcelerier** [comment]
nope that's my fault :p

**Comment by thibaudk** [comment]
Perfect ! 
All fixed, cheers !!
