### ISSUE TITLE
Assertion failed or segfault when loading score

### ISSUE THREAD

**Issue by fhars** [ossia/score#1071]
When I start ossia.score-3.0.0-a13-2-linux-amd64.AppImage with a new project and the pulseaudio backend, and then try to load any of the scores under USER LIBRARY -> Scores -> Tutorial, ossia score immediately terminates with either
```
Assertion 'pa_atomic_load(&(c)->_ref) >= 1' failed at pulse/context.c:283, function pa_context_ref(). Aborting.
Aborted (core dumped)
```
or
```
Segmentation fault (core dumped)
```

I have also seen that when switching between a new score and one from the "Recent files":
```
Assertion 'q->front' failed at pulsecore/queue.c:81, function pa_queue_push(). Aborting.                                                                                                                                         
Aborted (core dumped) 
```

**Comment by jcelerier** [comment]
Hello, 
thanks for the report, the pulseaudio backend is... alpha to say the least.
investigating.

**Comment by fhars** [comment]
There may be two bugs here: the one where the pulseaudio backend asserts, and the one where ossia.score segfaults once you try to load anything from the user library, which also happens with the jack backend:

```
Warning: Only C and default locale supported with the posix collation implementation (:0)
Warning: Only C and default locale supported with the posix collation implementation (:0)
Warning: Case insensitive sorting unsupported in the posix collation implementation (:0)
Warning: Numeric mode unsupported in the posix collation implementation (:0)
=== STOPPED PROCESS ==
=== STOPPED PROCESS ==
=== STOPPED PROCESS ==

[1]+  Segmentation fault      (core dumped) ossia-score
```

**Comment by fhars** [comment]
Here is a stacktrace from a debug build trying to load `triggers.score`:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007fa29f112864 in __GI_abort () at abort.c:79
#2  0x00007fa29f112749 in __assert_fail_base (fmt=0x7fa29f29e458 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x20c364f "IsArray()", file=0x20c0da2 "../3rdparty/libossia/3rdparty/rapidjson/include/rapidjson/document.h", line=1808, function=<optimized out>)
    at assert.c:92
#3  0x00007fa29f124a96 in __GI___assert_fail
    (assertion=0x20c364f "IsArray()", file=0x20c0da2 "../3rdparty/libossia/3rdparty/rapidjson/include/rapidjson/document.h", line=1808, function=0x20c6654 "rapidjson::GenericValue::Array rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::GetArray() [Encoding = rapidjson::UTF8<char>, Allocator = rapid"...) at assert.c:101
#4  0x000000000067d15f in rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::GetArray() (this=0x900ff60) at ../3rdparty/libossia/3rdparty/rapidjson/include/rapidjson/document.h:1808
#5  0x0000000000679f4e in score::DocumentManager::checkAndUpdateJson(rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >&, score::GUIApplicationContext const&) (obj=..., ctx=...)
    at ../src/lib/core/presenter/DocumentManager.cpp:522
#6  0x000000000064da6f in score::Document::loadModel(QString const&, score::DocumentDelegateFactory&) (this=0x8782210, fileName=..., factory=...) at ../src/lib/core/document/DocumentSerialization.cpp:227
#7  0x000000000064d3f3 in score::Document::Document(QString const&, score::DocumentDelegateFactory&, QWidget*, QObject*) (this=0x8782210, fileName=..., factory=..., parentview=0x402e760, parent=0x4477c60) at ../src/lib/core/document/DocumentSerialization.cpp:152
#8  0x0000000000643d6b in score::DocumentBuilder::loadDocument(score::GUIApplicationContext const&, QString, score::DocumentDelegateFactory&) (this=0x4477cc0, ctx=..., filename=..., doctype=...) at ../src/lib/core/document/DocumentBuilder.cpp:80
#9  0x000000000067ce72 in score::DocumentManager::loadDocument<QString const&, score::DocumentDelegateFactory&>(score::GUIApplicationContext const&, QString const&, score::DocumentDelegateFactory&) (this=0x4477c88, ctx=..., args=..., args=...)
    at ../src/lib/core/presenter/DocumentManager.hpp:76
#10 0x0000000000679b8e in score::DocumentManager::loadFile(score::GUIApplicationContext const&, QString const&) (this=0x4477c88, ctx=..., fileName=...) at ../src/lib/core/presenter/DocumentManager.cpp:464
#11 0x000000000079c27f in Library::LibraryDocumentLoader::onDoubleClick(QString const&, score::DocumentContext const&) (this=0x47943b0, path=..., ctx=...) at ../src/plugins/score-plugin-library/Library/LibraryInterface.cpp:58
#12 0x00000000007b601b in Library::SystemLibraryWidget::SystemLibraryWidget(score::GUIApplicationContext const&, QWidget*)::$_2::operator()(QModelIndex const&) const (this=0x4969a80, idx=...) at ../src/plugins/score-plugin-library/Library/SystemLibraryWidget.cpp:77
#13 0x00000000007b5e94 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<QModelIndex const&>, void, Library::SystemLibraryWidget::SystemLibraryWidget(score::GUIApplicationContext const&, QWidget*)::$_2>::call(Library::SystemLibraryWidget::SystemLibraryWidget(score::GUIApplicationContext const&, QWidget*)::$_2&, void**) (f=..., arg=0x7ffcb0e7a050) at /home/hars/Qt/5.14.1/gcc_64/include/QtCore/qobjectdefs_impl.h:146
#14 0x00000000007b5e61 in QtPrivate::Functor<Library::SystemLibraryWidget::SystemLibraryWidget(score::GUIApplicationContext const&, QWidget*)::$_2, 1>::call<QtPrivate::List<QModelIndex const&>, void>(Library::SystemLibraryWidget::SystemLibraryWidget(score::GUIApplicationContext const&, QWidget*)::$_2&, void*, void**) (f=..., arg=0x7ffcb0e7a050) at /home/hars/Qt/5.14.1/gcc_64/include/QtCore/qobjectdefs_impl.h:256
#15 0x00000000007b5e0c in QtPrivate::QFunctorSlotObject<Library::SystemLibraryWidget::SystemLibraryWidget(score::GUIApplicationContext const&, QWidget*)::$_2, 1, QtPrivate::List<QModelIndex const&>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*)
    (which=1, this_=0x4969a70, r=0x495fc30, a=0x7ffcb0e7a050, ret=0x0) at /home/hars/Qt/5.14.1/gcc_64/include/QtCore/qobjectdefs_impl.h:439
#16 0x00007fa29f79c2a0 in void doActivate<false>(QObject*, int, void**) () at /home/hars/Qt/5.14.1/gcc_64/lib/libQt5Core.so.5
#17 0x00007fa2a0b9a6e5 in QAbstractItemView::doubleClicked(QModelIndex const&) () at /home/hars/Qt/5.14.1/gcc_64/lib/libQt5Widgets.so.5
#18 0x00007fa2a0c0b7c9 in QTreeView::mouseDoubleClickEvent(QMouseEvent*) () at /home/hars/Qt/5.14.1/gcc_64/lib/libQt5Widgets.so.5
#19 0x00007fa2a099d059 in QWidget::event(QEvent*) () at /home/hars/Qt/5.14.1/gcc_64/lib/libQt5Widgets.so.5
#20 0x00007fa2a0a445ee in QFrame::event(QEvent*) () at /home/hars/Qt/5.14.1/gcc_64/lib/libQt5Widgets.so.5
#21 0x00007fa2a0ba682c in QAbstractItemView::viewportEvent(QEvent*) () at /home/hars/Qt/5.14.1/gcc_64/lib/libQt5Widgets.so.5
#22 0x00007fa2a0c0d43c in QTreeView::viewportEvent(QEvent*) () at /home/hars/Qt/5.14.1/gcc_64/lib/libQt5Widgets.so.5
#23 0x00007fa29f76568d in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () at /home/hars/Qt/5.14.1/gcc_64/lib/libQt5Core.so.5
#24 0x00007fa2a095d9d2 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /home/hars/Qt/5.14.1/gcc_64/lib/libQt5Widgets.so.5
#25 0x00007fa2a09655e8 in QApplication::notify(QObject*, QEvent*) () at /home/hars/Qt/5.14.1/gcc_64/lib/libQt5Widgets.so.5
#26 0x00007fa29f7658f8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /home/hars/Qt/5.14.1/gcc_64/lib/libQt5Core.so.5
#27 0x00007fa2a0963eca in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /home/hars/Qt/5.14.1/gcc_64/lib/libQt5Widgets.so.5
#28 0x00007fa2a09b5cb1 in QWidgetWindow::handleMouseEvent(QMouseEvent*) () at /home/hars/Qt/5.14.1/gcc_64/lib/libQt5Widgets.so.5
#29 0x00007fa2a09b88fb in QWidgetWindow::event(QEvent*) () at /home/hars/Qt/5.14.1/gcc_64/lib/libQt5Widgets.so.5
#30 0x00007fa2a095d9fc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /home/hars/Qt/5.14.1/gcc_64/lib/libQt5Widgets.so.5
#31 0x00007fa2a0964980 in QApplication::notify(QObject*, QEvent*) () at /home/hars/Qt/5.14.1/gcc_64/lib/libQt5Widgets.so.5
#32 0x00007fa29f7658f8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /home/hars/Qt/5.14.1/gcc_64/lib/libQt5Core.so.5
#33 0x00007fa2a0051413 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /home/hars/Qt/5.14.1/gcc_64/lib/libQt5Gui.so.5
#34 0x00007fa2a00524a5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /home/hars/Qt/5.14.1/gcc_64/lib/libQt5Gui.so.5
#35 0x00007fa2a002ee3b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /home/hars/Qt/5.14.1/gcc_64/lib/libQt5Gui.so.5
#36 0x00007fa29018e08a in xcbSourceDispatch(_GSource*, int (*)(void*), void*) () at /home/hars/Qt/5.14.1/gcc_64/lib/libQt5XcbQpa.so.5
#37 0x00007fa29b0704eb in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007fa29b070798 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#39 0x00007fa29b070863 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#40 0x00007fa29f7be3ec in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /home/hars/Qt/5.14.1/gcc_64/lib/libQt5Core.so.5
#41 0x00007fa29f764312 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /home/hars/Qt/5.14.1/gcc_64/lib/libQt5Core.so.5
#42 0x00007fa29f76d240 in QCoreApplication::exec() () at /home/hars/Qt/5.14.1/gcc_64/lib/libQt5Core.so.5
#43 0x000000000053c771 in Application::exec() (this=0x7ffcb0e7af30) at ../src/app/Application.cpp:620
#44 0x00000000005a592c in main(int, char**) (argc=1, argv=0x7ffcb0e7b0d8) at ../src/app/main.cpp:188
```

**Comment by jcelerier** [comment]
yep, for some reason the "save file version check" had been erroneously removed at some point, I reinstated it a few days ago (in master for now). Couldn't manage to make the pulseaudio backend crash however, but I should test on a machine with ubuntu.

**Comment by jcelerier** [comment]
found and fixed the pulseaudio crash (hopefully - I managed to reproduce something like it, and fixed it)
